USE [master]
GO

/****** Object:  Database [globons-app]    Script Date: 27/10/2017 20:16:24 ******/
CREATE DATABASE [globons-app]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'globons-app', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\globons-app.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'globons-app_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\globons-app_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [globons-app] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [globons-app].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [globons-app] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [globons-app] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [globons-app] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [globons-app] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [globons-app] SET ARITHABORT OFF 
GO

ALTER DATABASE [globons-app] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [globons-app] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [globons-app] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [globons-app] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [globons-app] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [globons-app] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [globons-app] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [globons-app] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [globons-app] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [globons-app] SET  DISABLE_BROKER 
GO

ALTER DATABASE [globons-app] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [globons-app] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [globons-app] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [globons-app] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [globons-app] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [globons-app] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [globons-app] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [globons-app] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [globons-app] SET  MULTI_USER 
GO

ALTER DATABASE [globons-app] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [globons-app] SET DB_CHAINING OFF 
GO

ALTER DATABASE [globons-app] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [globons-app] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [globons-app] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [globons-app] SET  READ_WRITE 
GO